/** Line translations for annotated transcript blocks (EN/RU). */
export const historiaBrasil500AnosBlockTranslations: Record<
  string,
  { en: string; ru: string }
> = {
  "par-1": {
    "en": "Hello, my dear friends, how are you? I'm Felipe Castanhari and I'd like to pose a challenge: did you know that you can summarize the entire history of Brazil in just four little things? Go on, try it… FHC, Lula, Dilma, Temer? No. Pelé, Romário, Ronaldinho, Neymar? No. If you have no idea what these four things are, this video is especially for you. Nostalgia is finally back — and today I'm going to tell 500 years of history in just one hour. Of course, I can't say absolutely everything in one hour, but I'm going to go through the most important steps and show how they connect. So enough stalling: let's get started.",
    "ru": "Привет, мои дорогие друзья, как ваши дела? Я Фелипе Кастанари, и я хотел бы поставить задачу: знаете ли вы, что всю историю Бразилии можно изложить всего в четырех маленьких вещах? Давай, попробуй… ФХК, Лула, Дилма, Темер? Нет. Пеле, Ромарио, Роналдиньо, Неймар? Нет. Если вы понятия не имеете, что это за четыре вещи, это видео специально для вас. Ностальгия наконец-то вернулась — и сегодня я расскажу 500-летнюю историю всего за один час. Конечно, я не смогу рассказать абсолютно всё за один час, но я собираюсь пройтись по самым важным шагам и показать, как они связаны. Итак, хватит медлить: давайте начнем."
  },
  "par-2": {
    "en": "Before talking about these four things, you need to understand how the history of Brazil works. Let's pretend that this whole story is a person — and that person, like you and me, has two legs that support their entire body. One of these legs is the economy: how the wealth of these people is produced. In the case of Brazil, these are raw materials exported all over the world. The other leg is political power: who governs the people. These two legs go together, because here whoever controls the raw materials also controls the country. That's why there were 500 years of conflicts: at all times, everyone wanted a raw material to call their own.",
    "ru": "Прежде чем говорить об этих четырех вещах, вам необходимо понять, как устроена история Бразилии. Давайте представим, что вся эта история — это человек, и у этого человека, как и у нас с вами, есть две ноги, которые поддерживают все его тело. Одной из этих опор является экономика: как производится богатство этих людей. В случае с Бразилией это сырье, экспортируемое по всему миру. Другая нога – политическая власть: кто управляет людьми. Эти две ноги идут вместе, потому что здесь тот, кто контролирует сырье, контролирует и страну. Вот почему были 500 лет конфликтов: во все времена каждому хотелось иметь сырье, которое можно было бы назвать своим."
  },
  "par-3": {
    "en": "After this introduction it becomes easier to discover the four things that summarize the history of Brazil: brazilwood, sugar cane, gold and coffee. These products don't tell all the details, but they help a lot to see how history was written — at least after the Europeans arrived. Because it is obvious: the history of Brazil did not begin in 1500.",
    "ru": "После этого вступления становится легче открыть для себя четыре вещи, которые обобщают историю Бразилии: бразильское дерево, сахарный тростник, золото и кофе. Эти продукты не рассказывают всех подробностей, но они очень помогают увидеть, как писалась история — по крайней мере, после прибытия европейцев. Потому что очевидно: история Бразилии началась не в 1500 году."
  },
  "par-4": {
    "en": "Everyone knows that there were people here before the Portuguese. There are archaeological sites that show very ancient occupation. Studies indicate human presence around 45 thousand years ago. The Serra da Capivara National Park, in the southeast of Piauí, has more than 400 sites and the largest concentration of cave paintings in the world — traces of human occupation dating back around 50 thousand years. This is Brazilian prehistory. Over the millennia, these societies became organized — and now I'm talking about indigenous peoples.",
    "ru": "Всем известно, что люди здесь были и до португальцев. Есть археологические памятники, свидетельствующие об очень древней оккупации. Исследования указывают на присутствие человека около 45 тысяч лет назад. Национальный парк Серра-да-Капивара, расположенный на юго-востоке Пиауи, имеет более 400 памятников и самую большую в мире концентрацию наскальных рисунков — следов человеческой деятельности, насчитывающих около 50 тысяч лет. Это предыстория Бразилии. За тысячелетия эти общества стали организованными — и теперь я говорю о коренных народах."
  },
  "par-5": {
    "en": "Historians estimate that around 1500 there were around 5 million indigenous people in the territory that is today Brazil; Today the indigenous population is much smaller. These people formed nations divided into several groups. That talk that they lived in absolute peace before the Europeans doesn't match the truth: there was a lot of bad blood between tribes, because they were always coming out on top — or with a bow and arrow — in the dispute over territories. But, in 1500, some indigenous people saw caravels on the horizon... and barely suspected what was coming.",
    "ru": "По оценкам историков, около 1500 г. на территории нынешней Бразилии проживало около 5 миллионов коренных жителей; Сегодня коренное население значительно меньше. Эти люди образовали нации, разделенные на несколько групп. Разговоры о том, что до европейцев они жили в абсолютном мире, не соответствуют истине: между племенами было много вражды, потому что в споре о территориях они всегда выходили победителями — или с луком и стрелами. Но в 1500 году некоторые коренные жители увидели на горизонте каравеллы... и едва подозревали, что их ждет."
  },
  "par-6": {
    "en": "At the end of the 15th century, Europe's most valuable products were spices from the Indies — as Europeans called the East. Everyone wanted a direct route to commercialize these products. The ships set out with the mission of opening routes and conquering new lands. Portugal and Spain were in charge of the oceans; They fought so much that even the Pope had to enter the field and help divide the world between the two. This is the famous Treaty of Tordesillas, made shortly after the discovery of America: an imaginary line on the map — land on one side for Portugal, on the other for Spain.",
    "ru": "В конце XV века самым ценным продуктом Европы были специи из Индии — так европейцы называли Восток. Все хотели иметь прямой путь к коммерциализации этих продуктов. Корабли отправились с миссией открытия путей и завоевания новых земель. Португалия и Испания отвечали за океаны; Они сражались так сильно, что даже Папе пришлось выйти на поле боя и помочь разделить мир между ними. Это знаменитый Тордесильясский договор, заключенный вскоре после открытия Америки: воображаемая линия на карте — земля с одной стороны Португалии, с другой Испании."
  },
  "par-7": {
    "en": "It was with this treaty in its pocket that a Portuguese fleet led by Pedro Álvares Cabral arrived in what is now Bahia, on April 22, 1500. We call this the «discovery of Brazil», but the story is told from the point of view of the Europeans — the territory and indigenous peoples had already existed for a long time. In practice, these navigators were conquerors who took possession of new lands in the name of the king. Many people believe that Cabral was lost by accident; Several theories say that Portugal already knew about the land and came to take it. This first little role lasted about 10 days: they explored, spoke to natives, said masses and declared the land “Ilha de Vera Cruz” — but Brazil was almost abandoned for around 30 years.",
    "ru": "Именно с этим договором в кармане 22 апреля 1500 года португальский флот под предводительством Педро Альвареша Кабрала прибыл на территорию нынешней Баии. Мы называем это «открытием Бразилии», но история рассказана с точки зрения европейцев — территория и коренные народы существовали уже давно. На практике эти мореплаватели были завоевателями, завладевшими новыми землями от имени короля. Многие считают, что Кабрал пропал случайно; Некоторые теории говорят, что Португалия уже знала об этой земле и пришла забрать ее. Эта первая маленькая роль длилась около 10 дней: они исследовали территорию, разговаривали с местными жителями, служили мессы и провозгласили землю «Илья-де-Вера-Крус» — но Бразилия была почти заброшена примерно на 30 лет."
  },
  "par-8": {
    "en": "Portugal's enthusiasm cooled when it did not find gold on the coast. Then their eyes really grew when they noticed a peculiar tree: the brazilwood, which produced red dye for dyeing fabrics and was worth a lot. The coast was full of them. The Portuguese had a party and came to explore the wood — in practice, those who felled it were indigenous people, in exchange for trinkets and iron axes. Thus, the Island of Vera Cruz / Terra de Santa Cruz became the Land of Brazil and, later, simply Brazil. When the French also began to explore Brazilwood, Portugal realized that the only way to stop this was to send people to actually occupy the land.",
    "ru": "Энтузиазм Португалии остыл, когда она не нашла золота на побережье. Затем их глаза по-настоящему расширились, когда они заметили своеобразное дерево: бразильское дерево, из которого производили красную краску для крашения тканей и которое стоило очень много. Побережье было полно их. Португальцы устроили вечеринку и пришли исследовать лес — на самом деле его вырубали коренные жители в обмен на безделушки и железные топоры. Таким образом, остров Вера-Крус/Терра-де-Санта-Крус стал Землей Бразилии, а позже и просто Бразилии. Когда французы также начали осваивать Бразильский лес, Португалия поняла, что единственный способ остановить это — отправить людей фактически оккупировать эту землю."
  },
  "par-9": {
    "en": "In 1530, Martim Afonso de Sousa disembarked and founded São Vicente (1532), the first village. To colonize without spending out of his own pocket, the king divided Brazil into strips called hereditary captaincies and handed it over to grantees: they were supposed to populate, protect and make the land profitable for the king. Almost only São Vicente and Pernambuco actually profited. Then came the political step: a governor-general for the entire colony. The most remembered at the school are Tomé de Sousa, Duarte da Costa and Mem de Sá. Tomé de Sousa founded Salvador, the first capital. The first Jesuits also arrived.",
    "ru": "В 1530 году Мартим Афонсу де Соуза высадился на берег и основал первую деревню Сан-Висенте (1532 г.). Чтобы колонизировать, не тратя из собственного кармана, король разделил Бразилию на полосы, называемые наследственными капитанствами, и передал ее грантополучателям: они должны были заселять, защищать и делать землю прибыльной для короля. Практически только Сан-Висенте и Пернамбуку действительно получили прибыль. Затем последовал политический шаг: назначение генерал-губернатора всей колонии. Наиболее помнят в школе Томе де Соуза, Дуарте да Коста и Мем де Са. Томе де Соуза основал Сальвадор, первую столицу. Прибыли и первые иезуиты."
  },
  "par-10": {
    "en": "In the 16th century, the Catholic Church stood hand in hand with Portugal and Spain: where one went, the church followed. The Jesuits came to catechize the indigenous people. Cross and sword — a strong metaphor in the video — point to conquest: the sword against those who resisted, the cross to convert. The Portuguese were not at all concerned with preserving indigenous culture. And then comes the second item on the list: sugar cane. Coastal soil and climate were ideal; Sugar was worth a lot in Europe and became the colony's main activity, especially in the Northeast. It is impossible to talk about this without talking about slavery: first of indigenous people, then — with the growth of plantations around 1550 — of African trafficking, because the colonists needed labor to handle so much production — and trafficking itself was one of the most profitable businesses at the time.",
    "ru": "В 16 веке католическая церковь стояла рука об руку с Португалией и Испанией: куда бы ни шёл один, туда следовала и церковь. Иезуиты пришли катехизировать коренное население. Крест и меч — сильная метафора в видео — указывают на завоевание: меч против тех, кто сопротивлялся, крест для обращения. Португальцы совершенно не заботились о сохранении местной культуры. И затем идет второй пункт в списке: сахарный тростник. Прибрежные почвы и климат были идеальными; Сахар ценился в Европе очень дорого и стал основным видом деятельности колонии, особенно на северо-востоке. Невозможно говорить об этом, не говоря о рабстве: сначала коренного населения, затем — с ростом плантаций около 1550 года — африканской торговли людьми, поскольку колонистам требовалась рабочая сила для обработки такого большого количества продукции, — а сама торговля людьми была одним из самых прибыльных видов бизнеса в то время."
  }
};
