import type { ReadingExpressionGuide } from "./types";

export const historiaBrasil500AnosExpressionGuide: ReadingExpressionGuide = {
  sectionTitle: "Expressões do vídeo",
  intro:
    "Glossário com tradução em inglês e russo — use depois de ouvir/ler para fixar vocabulário histórico e gírias brasileiras da narração.",
  entries: [
    {
      id: "chega-de-enrolar",
      portuguese: "chega de enrolar",
      english: "enough stalling / let's get to it",
      russian: "хватит тянуть / давайте уже",
      example: "Então chega de enrolar: vamos começar agora o nosso vídeo.",
      explanation: "Colloquial way to say stop delaying and start.",
    },
    {
      id: "fazer-de-conta-que",
      portuguese: "fazer de conta que",
      english: "to pretend that / to imagine that",
      russian: "представить, что / сделать вид, что",
      example: "Vamos fazer de conta que toda essa história é uma pessoa.",
      explanation: "Invites the listener to accept a simplifying metaphor.",
    },
    {
      id: "materias-primas",
      portuguese: "matérias-primas",
      english: "raw materials / commodities",
      russian: "сырьё / сырьевые товары",
      example: "No caso do Brasil, são as matérias-primas que foram exportadas pro mundo inteiro.",
      explanation: "Goods extracted/produced for export before industrial processing.",
    },
    {
      id: "andar-juntas",
      portuguese: "andar juntas",
      english: "go hand in hand",
      russian: "идти рука об руку",
      example: "Essas duas pernas andam juntas, porque quem controla as matérias-primas também controla o país.",
      explanation: "Two things develop or operate together.",
    },
    {
      id: "para-chamar-de-sua",
      portuguese: "para chamar de sua",
      english: "to call one's own",
      russian: "чтобы назвать своим",
      example: "Todo mundo, em todas as épocas, queria uma matéria-prima para chamar de sua.",
      explanation: "Wanting exclusive ownership of something.",
    },
    {
      id: "sitios-arqueologicos",
      portuguese: "sítios arqueológicos",
      english: "archaeological sites",
      russian: "археологические памятники / стоянки",
      example: "Existem sítios arqueológicos que mostram que os primeiros brasileiros são muito antigos.",
      explanation: "Places where material remains of past human activity are studied.",
    },
    {
      id: "vestigios-de-ocupacao",
      portuguese: "vestígios de ocupação",
      english: "traces of occupation / settlement remains",
      russian: "следы заселения / обитания",
      example: "São vestígios de ocupação humana que datam de cerca de 50 mil anos.",
      explanation: "Physical evidence that people lived somewhere.",
    },
    {
      id: "nao-condiz-com-a-verdade",
      portuguese: "não condiz com a verdade",
      english: "does not match the truth",
      russian: "не соответствует правде",
      example: "Aquele papinho de que os índios viviam em paz… não condiz com a verdade.",
      explanation: "Says a claim is factually wrong.",
    },
    {
      id: "a-treta-rolava-solta",
      portuguese: "a treta rolava solta",
      english: "conflict was rampant / beef was everywhere",
      russian: "конфликты шли полным ходом",
      example: "A treta entre as tribos rolava solta.",
      explanation: "Very colloquial: fights/disputes were common and open.",
    },
    {
      id: "sair-na-mao",
      portuguese: "sair na mão",
      english: "to get into a fight (with fists)",
      russian: "лезть в драку",
      example: "Os índios estavam sempre saindo na mão… na disputa de melhores territórios.",
      explanation: "Colloquial for physical fighting.",
    },
    {
      id: "entrar-em-campo",
      portuguese: "entrar em campo",
      english: "to step in / get involved",
      russian: "вступить в игру / вмешаться",
      example: "Até o Papa teve que entrar em campo e ajudar a fazer um acordo.",
      explanation: "Metaphor from sports: intervene in a dispute.",
    },
    {
      id: "tratar-de-tordesilhas",
      portuguese: "Tratado de Tordesilhas",
      english: "Treaty of Tordesillas",
      russian: "Тордесильясский договор",
      example: "Esse é o famoso Tratado de Tordesilhas, feito logo depois da descoberta da América.",
      explanation: "1494 agreement dividing overseas lands between Portugal and Spain.",
    },
    {
      id: "tomar-posse-de",
      portuguese: "tomar posse de",
      english: "to take possession of",
      russian: "вступить во владение / захватить",
      example: "Esses navegantes eram, na verdade, conquistadores que tomavam posse de novas terras em nome do rei.",
      explanation: "Formal claim of ownership, often colonial.",
    },
    {
      id: "do-ponto-de-vista-de",
      portuguese: "do ponto de vista de",
      english: "from the point of view of",
      russian: "с точки зрения",
      example: "A gente chama essa data de «descobrimento» porque a história é contada do ponto de vista dos europeus.",
      explanation: "Frames whose perspective shapes the narrative.",
    },
    {
      id: "crescer-o-olho",
      portuguese: "crescer o olho",
      english: "to covet / get greedy for",
      russian: "зариться / положить глаз",
      example: "Eles cresceram o olho de verdade quando perceberam que tinha uma árvore bem peculiar aqui.",
      explanation: "Colloquial: suddenly want something strongly.",
    },
    {
      id: "fazer-a-festa",
      portuguese: "fazer a festa",
      english: "to go all out / cash in",
      russian: "устроить пир / поживиться",
      example: "Os portugueses fizeram a festa e começaram a vir para cá só para pegar o pau-brasil.",
      explanation: "Colloquial: exploit an opportunity enthusiastically.",
    },
    {
      id: "bugigangas",
      portuguese: "bugigangas",
      english: "trinkets / cheap gadgets",
      russian: "безделушки / побрякушки",
      example: "Os índios trabalhavam em troca de bugigangas.",
      explanation: "Small low-value objects offered in unequal trade.",
    },
    {
      id: "se-ligar-que",
      portuguese: "se ligar que",
      english: "to realize that / catch on that",
      russian: "врубиться / понять, что",
      example: "Portugal se ligou que a única maneira de impedir isso seria mandando gente para cá.",
      explanation: "Colloquial BR: become aware of something important.",
    },
    {
      id: "capitanias-hereditarias",
      portuguese: "capitanias hereditárias",
      english: "hereditary captaincies",
      russian: "наследственные капитанства",
      example: "A solução foi dividir o Brasil em faixas de terra chamadas capitanias hereditárias.",
      explanation: "Colonial land grants passed within a family, under the crown.",
    },
    {
      id: "dar-lucro",
      portuguese: "dar lucro",
      english: "to turn a profit",
      russian: "приносить прибыль",
      example: "Eles tinham a obrigação de fazer aquela terra dar lucro pro rei.",
      explanation: "Generate financial return.",
    },
    {
      id: "de-maos-dadas",
      portuguese: "de mãos dadas",
      english: "hand in hand",
      russian: "рука об руку",
      example: "A Igreja Católica ficava de mãos dadas o tempo inteiro com Portugal e Espanha.",
      explanation: "Close alliance; acting together.",
    },
    {
      id: "catequizar",
      portuguese: "catequizar",
      english: "to catechize / convert (to Catholicism)",
      russian: "катехизировать / обращать в католицизм",
      example: "Os jesuítas vinham para cá com o objetivo de catequizar os índios.",
      explanation: "Teach Christian doctrine to convert people.",
    },
    {
      id: "nem-um-pouco",
      portuguese: "nem um pouco",
      english: "not at all",
      russian: "нисколько / ничуть",
      example: "Os portugueses não estavam nem um pouco preocupados em manter a cultura dos índios.",
      explanation: "Strong negation of degree.",
    },
    {
      id: "mao-de-obra",
      portuguese: "mão de obra",
      english: "labor / workforce",
      russian: "рабочая сила",
      example: "Os portugueses precisavam de mão de obra para dar conta de tanta produção.",
      explanation: "People available to do the work, often in economic contexts.",
    },
    {
      id: "dar-conta-de",
      portuguese: "dar conta de",
      english: "to manage / cope with",
      russian: "справиться с",
      example: "Precisavam de mão de obra para dar conta de tanta produção.",
      explanation: "Be able to handle a task or volume of work.",
    },
  ],
};
